const EXISTING = [
  "20MICRONS.NS","21STCENMGM.NS","3IINFOLTD.NS","3MINDIA.NS","5PAISA.NS",
  "AARTIDRUGS.NS","AARTIIND.NS","AARTIPHARM.NS","AARTISURF.NS","AAVAS.NS",
  "ABB.NS","ABBOTINDIA.NS","ABCAPITAL.NS","ABFRL.NS","ABREL.NS",
  "ACC.NS","ADANIENT.NS","ADANIGREEN.NS","ADANIPORTS.NS","ADANIPOWER.NS",
  "ADFFOODS.NS","ADVENZYMES.NS","AEGISLOG.NS","AETHER.NS","AFFLE.NS",
  "AGI.NS","AJANTPHARM.NS","AKZOINDIA.NS","ALKEM.NS","ALKYLAMINE.NS",
  "ALLCARGO.NS","ALOKINDS.NS","AMBUJACEM.NS","ANGELONE.NS","ANURAS.NS",
  "APARINDS.NS","APLLTD.NS","APOLLOHOSP.NS","APOLLOTYRE.NS","APTUS.NS",
  "ASAHIINDIA.NS","ASHOKLEY.NS","ASIANPAINT.NS","ASTRAL.NS","ATGL.NS",
  "ATUL.NS","AUBANK.NS","AUROPHARMA.NS","AXISBANK.NS","BAJAJ-AUTO.NS",
  "BAJAJFINSV.NS","BAJFINANCE.NS","BALKRISIND.NS","BALRAMCHIN.NS","BANDHANBNK.NS",
  "BANKBARODA.NS","BEL.NS","BERGEPAINT.NS","BHARATFORG.NS","BHARTIARTL.NS",
  "BHEL.NS","BIOCON.NS","BLUEDART.NS","BLUESTARCO.NS","BOSCHLTD.NS",
  "BPCL.NS","BRITANNIA.NS","CAMS.NS","CANBK.NS","CANFINHOME.NS",
  "CARBORUNIV.NS","CEATLTD.NS","CENTRALBK.NS","CIPLA.NS","COALINDIA.NS",
  "COFORGE.NS","COLPAL.NS","CONCOR.NS","COROMANDEL.NS","CROMPTON.NS",
  "CUMMINSIND.NS","CYIENT.NS","DABUR.NS","DALBHARAT.NS","DEEPAKFERT.NS",
  "DEEPAKNTR.NS","DELHIVERY.NS","DIVISLAB.NS","DIXON.NS","DLF.NS",
  "DRREDDY.NS","EICHERMOT.NS","EIDPARRY.NS","ESCORTS.NS","EXIDEIND.NS",
  "FEDERALBNK.NS","FINCABLES.NS","GAIL.NS","GLENMARK.NS","GMRP&UI.NS",
  "GODREJCP.NS","GODREJPROP.NS","GRASIM.NS","GUJGASLTD.NS","HAL.NS",
  "HAVELLS.NS","HCLTECH.NS","HDFCAMC.NS","HDFCBANK.NS","HDFCLIFE.NS",
  "HEROMOTOCO.NS","HINDALCO.NS","HINDPETRO.NS","HINDUNILVR.NS","ICICIBANK.NS",
  "ICICIGI.NS","ICICIPRULI.NS","IDFCFIRSTB.NS","IGL.NS","INDIGO.NS",
  "INDUSINDBK.NS","INFY.NS","IOC.NS","IRCTC.NS","IRFC.NS",
  "ITC.NS","JINDALSTEL.NS","JSWENERGY.NS","JSWSTEEL.NS","JUBLFOOD.NS",
  "KALYANKJIL.NS","KEC.NS","KOTAKBANK.NS","KPITTECH.NS","LALPATHLAB.NS",
  "LICHSGFIN.NS","LICI.NS","LODHA.NS","LT.NS","LTIM.NS",
  "LTTS.NS","LUPIN.NS","M&M.NS","MANKIND.NS","MARICO.NS",
  "MARUTI.NS","MAZDOCK.NS","MCX.NS","METROPOLIS.NS","MGL.NS",
  "MPHASIS.NS","MRF.NS","MUTHOOTFIN.NS","NAUKRI.NS","NESTLEIND.NS",
  "NHPC.NS","NMDC.NS","NTPC.NS","NYKAA.NS","OBEROIRLTY.NS",
  "ONGC.NS","PAGEIND.NS","PAYTM.NS","PERSISTENT.NS","PETRONET.NS",
  "PFC.NS","PIDILITIND.NS","PIIND.NS","POLYCAB.NS","POWERGRID.NS",
  "RECLTD.NS","RELIANCE.NS","RBLBANK.NS","SBIN.NS","SBICARD.NS",
  "SBILIFE.NS","SHRIRAMFIN.NS","SIEMENS.NS","SRF.NS","SUNPHARMA.NS",
  "SUPREMEIND.NS","SUZLON.NS","TATACOMM.NS","TATACONSUM.NS","TATAELXSI.NS",
  "TATAMOTORS.NS","TATAPOWER.NS","TATASTEEL.NS","TCS.NS","TECHM.NS",
  "TITAN.NS","TORNTPHARM.NS","TRENT.NS","TVSMOTOR.NS","UBL.NS",
  "ULTRACEMCO.NS","UPL.NS","VEDL.NS","VOLTAS.NS","WIPRO.NS","ZOMATO.NS"
];

const MORE_STOCKS = [
  "ABBOTINDIA.NS","AEGISLOG.NS","AIAENG.NS","ALKYLAMINE.NS","AMARAJABAT.NS",
  "AMBER.NS","ANANDRATHI.NS","APOLLOPIPE.NS","APOLLOTYRE.NS","APTUS.NS",
  "ASHOKA.NS","ASTRAZEN.NS","AUBANK.NS","AVANTIFEED.NS","BALAMINES.NS",
  "BATAINDIA.NS","BAYERCROP.NS","BDL.NS","BEL.NS","BEML.NS",
  "BERGEPAINT.NS","BIRLACORPN.NS","BLUEDART.NS","BRIGADE.NS","CANFINHOME.NS",
  "CARBORUNIV.NS","CEATLTD.NS","CENTURYPLY.NS","CERA.NS","CGPOWER.NS",
  "CHALET.NS","CHAMBLFERT.NS","CIEINDIA.NS","CLEAN.NS","COFORGE.NS",
  "COROMANDEL.NS","CROMPTON.NS","CYIENT.NS","DABUR.NS","DALBHARAT.NS",
  "DEEPAKFERT.NS","DEEPAKNTR.NS","DIVISLAB.NS","DIXON.NS","DLF.NS",
  "DRREDDY.NS","ECLERX.NS","EICHERMOT.NS","EIDPARRY.NS","ESCORTS.NS",
  "EXIDEIND.NS","FINCABLES.NS","FORTIS.NS","GAIL.NS","GLENMARK.NS",
  "GODREJCP.NS","GODREJPROP.NS","GRANULES.NS","GRASIM.NS","GSPL.NS",
  "GUJGASLTD.NS","HAL.NS","HAVELLS.NS","HCLTECH.NS","HDFCAMC.NS",
  "HDFCLIFE.NS","HEROMOTOCO.NS","HINDALCO.NS","HINDCOPPER.NS","HINDPETRO.NS",
  "ICICIGI.NS","ICICIPRULI.NS","IDFCFIRSTB.NS","IGL.NS","INDIGO.NS",
  "INDUSINDBK.NS","IRCON.NS","IRFC.NS","ITC.NS","JBCHEPHARM.NS",
  "JINDALSTEL.NS","JKCEMENT.NS","JUBLFOOD.NS","KAJARIACER.NS","KALYANKJIL.NS",
  "KEC.NS","KNRCON.NS","KPITTECH.NS","LALPATHLAB.NS","LAURUSLABS.NS",
  "LICHSGFIN.NS","LODHA.NS","LT.NS","LTIM.NS","LTTS.NS",
  "LUPIN.NS","M&MFIN.NS","MANAPPURAM.NS","MANKIND.NS","MARICO.NS",
  "MAZDOCK.NS","MCX.NS","METROPOLIS.NS","MGL.NS","MPHASIS.NS",
  "MRF.NS","MUTHOOTFIN.NS","NAUKRI.NS","NATCOPHARM.NS","NESTLEIND.NS",
  "NHPC.NS","NMDC.NS","NTPC.NS","OBEROIRLTY.NS","ONGC.NS",
  "PAGEIND.NS","PERSISTENT.NS","PETRONET.NS","PFC.NS","PIDILITIND.NS",
  "PIIND.NS","POLYCAB.NS","POWERGRID.NS","RAMCOCEM.NS","RECLTD.NS",
  "RITES.NS","SBICARD.NS","SBILIFE.NS","SHREECEM.NS","SHRIRAMFIN.NS",
  "SIEMENS.NS","SRF.NS","SUNPHARMA.NS","SUPREMEIND.NS","SUZLON.NS",
  "TATACOMM.NS","TATACONSUM.NS","TATAELXSI.NS","TATAPOWER.NS","TATASTEEL.NS",
  "TCS.NS","TECHM.NS","TITAN.NS","TORNTPHARM.NS","TRENT.NS",
  "TVSMOTOR.NS","UBL.NS","ULTRACEMCO.NS","UPL.NS","VEDL.NS",
  "VOLTAS.NS","WIPRO.NS","ZENSARTECH.NS","ZOMATO.NS"
];

// Find duplicates within MORE_STOCKS itself
const moreSet = new Set();
const selfDupes = [];
MORE_STOCKS.forEach(s => { if (moreSet.has(s)) selfDupes.push(s); else moreSet.add(s); });

// Find overlap between MORE_STOCKS and EXISTING
const existingSet = new Set(EXISTING);
const crossDupes = MORE_STOCKS.filter(s => existingSet.has(s));

// Genuinely new stocks
const newOnly = MORE_STOCKS.filter(s => !existingSet.has(s));

// Final merged unique list (sorted)
const merged = [...new Set([...EXISTING, ...MORE_STOCKS])].sort();

console.log("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━");
console.log("📋 EXISTING list size   :", EXISTING.length);
console.log("📋 MORE_STOCKS size     :", MORE_STOCKS.length);
console.log("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━");
console.log("⚠️  Self-dupes in MORE  :", selfDupes.length ? selfDupes.join(", ") : "NONE ✅");
console.log("⚠️  Cross-dupes (overlap):", crossDupes.length, "→", crossDupes.join(", "));
console.log("✅  Genuinely new stocks:", newOnly.length, "→", newOnly.join(", "));
console.log("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━");
console.log("🎯 Final merged total   :", merged.length, "unique stocks");
console.log("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━");
